/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新規登録（Nest JWT 発行） */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログイン（Nest JWT 発行） */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 現在のユーザー（X-API-Key + Nest JWT） */
        post: operations["AuthController_me"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/admin/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 管理者のみ（403 = ロール不足） */
        get: operations["AuthController_adminPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthUserSummaryDto: {
            /** @example uuid */
            id: string;
            /** @example user@example.com */
            email: string;
            /**
             * @example tenant_admin
             * @enum {string}
             */
            role:
                | "platform_admin"
                | "tenant_admin"
                | "approver"
                | "applicant";
            /** @example uuid */
            tenantId: string;
        };
        AuthIssueTokensResponseDto: {
            /** @description Nest が発行した JWT */
            access_token: string;
            user: components["schemas"]["AuthUserSummaryDto"];
        };
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            /** @example password12 */
            password: string;
            /** @example Acme Inc */
            organizationName?: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example password12 */
            password: string;
            /** Format: uuid */
            tenantId?: string;
        };
        AuthMeResponseDto: {
            id: string;
            email: string;
            /**
             * @example [
             *       "user"
             *     ]
             */
            roles: string[];
            tenantId: string;
        };
        AdminPingResponseDto: {
            /** @example true */
            ok: boolean;
        };
        ErrorResponseDto: {
            /**
             * @description HTTP ステータス（レスポンスのステータスラインと一致）
             * @example 401
             */
            statusCode: number;
            /**
             * @description ユーザー向けメッセージ（バリデーション時は文字列の配列になり得る）
             * @example Invalid email or password
             */
            message: string | string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example 200
                         * @enum {number}
                         */
                        status: 200;
                        data: components["schemas"]["AuthIssueTokensResponseDto"];
                    };
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example 200
                         * @enum {number}
                         */
                        status: 200;
                        data: components["schemas"]["AuthIssueTokensResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example 200
                         * @enum {number}
                         */
                        status: 200;
                        data: components["schemas"]["AuthIssueTokensResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example 200
                         * @enum {number}
                         */
                        status: 200;
                        data: components["schemas"]["AuthMeResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_adminPing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example 200
                         * @enum {number}
                         */
                        status: 200;
                        data: components["schemas"]["AdminPingResponseDto"];
                    };
                };
            };
        };
    };
}
