import type { AuditLog } from '../../../../models/entities/audit-log.entity';
import type { AuditLogItemDto } from '../dto/audit-logs.dto';

export function mapAuditLogToDto(row: AuditLog): AuditLogItemDto {
  return {
    id: row.id,
    groupId: row.groupId,
    actorUserId: row.actorUserId,
    actorEmail: row.actorUser?.email ?? null,
    actorType: row.actorType ?? 'user',
    actorEmailSnapshot: row.actorEmailSnapshot,
    actionType: row.actionType,
    targetType: row.targetType,
    targetId: row.targetId,
    scopeType: row.scopeType,
    scopeId: row.scopeId,
    resourceType: row.resourceType,
    resourceId: row.resourceId,
    resourceLabel: row.resourceLabelSnapshot,
    operation: row.operation,
    outcome: row.outcome ?? 'success',
    actor: row.actorJson,
    resource: row.resourceJson,
    changes: row.changesJson,
    targetUserId: row.targetUserId,
    targetEmailSnapshot: row.targetEmailSnapshot,
    applicationId: row.applicationId,
    statusFrom: row.statusFrom,
    statusTo: row.statusTo,
    stepOrderFrom: row.stepOrderFrom,
    stepOrderTo: row.stepOrderTo,
    roleFrom: row.roleFrom,
    roleTo: row.roleTo,
    groupRoleFrom: row.groupRoleFrom,
    groupRoleTo: row.groupRoleTo,
    summary: row.summary,
    metadataJson: row.metadataJson,
    createdAt: row.createdAt.toISOString(),
  };
}
